In [1]:
# https://www.numpy.org/devdocs/user/quickstart.html
import numpy as np

# Ways to Create Array in Numpy

In [2]:
x1 = np.array([2,4,7,8,43,56,78,32,67])

In [3]:
print(x1)

[ 2  4  7  8 43 56 78 32 67]


In [4]:
x2 = np.array([i for i in range(1,100001) if i % 2 == 0])

In [5]:
len(x2)

50000

In [6]:
x2[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
x3 = np.arange(2,10001,2)

In [8]:
len(x3)

5000

In [9]:
x3[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
# will return array of 50 numbers starting from 1.0 to 10.0
# x4 = np.linspace(1,10)

# will return array of 20 numbers starting from 1.0 to 10.0
x4 = np.linspace(1,10, num=20, retstep=True)

In [11]:
x4

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [12]:
np.random.rand(2,5,3)

array([[[0.92856612, 0.16385024, 0.6799138 ],
        [0.22987177, 0.69843408, 0.61531602],
        [0.32601511, 0.06354566, 0.49430566],
        [0.60455672, 0.31529723, 0.43458193],
        [0.02920964, 0.17650307, 0.96393975]],

       [[0.25935834, 0.33398078, 0.34562222],
        [0.86148496, 0.82223427, 0.08653278],
        [0.23223048, 0.67423527, 0.19324662],
        [0.52465348, 0.229233  , 0.05655192],
        [0.37817739, 0.88957135, 0.92512403]]])

In [13]:
# will return 5 random numbers between 10 and 100
np.random.randint(10,100,5)

array([57, 45, 36, 51, 24])

In [14]:
np.random.seed(5)
np.random.randint(10,100,5)

array([88, 71, 26, 83, 18])

In [15]:
np.random.randint(10,100,5)

array([72, 37, 40, 90, 17])

In [16]:
np.random.rand()*255

252.6593373557099

In [17]:
np.random.seed(5)
np.random.rand()

0.22199317108973948

In [18]:
np.random.rand()

0.8707323061773764

In [19]:
np.random.random([5,5])

array([[0.20671916, 0.91861091, 0.48841119, 0.61174386, 0.76590786],
       [0.51841799, 0.2968005 , 0.18772123, 0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987, 0.87993703, 0.27408646, 0.41423502],
       [0.29607993, 0.62878791, 0.57983781, 0.5999292 , 0.26581912],
       [0.28468588, 0.25358821, 0.32756395, 0.1441643 , 0.16561286]])

# Methods of Numpy

In [20]:
x = np.random.randint(10,1000,200)

In [21]:
x.max()

997

In [22]:
x.min()

23

In [23]:
x.mean()

499.775

In [24]:
x.shape

(200,)

In [25]:
x.ndim

1

In [26]:
x.argmax()

155

In [27]:
x[157]

695

In [28]:
x.argmin()

95

In [29]:
x.argsort()[:10]

array([ 95,  35, 198, 102, 195,  80, 190,  51,  52, 112], dtype=int64)

# Slicing Numpy Array

In [30]:
x = np.array([[4,5,3,2],[6,8,3,6],[8,8,4,7]])

In [31]:
x

array([[4, 5, 3, 2],
       [6, 8, 3, 6],
       [8, 8, 4, 7]])

In [32]:
x.ndim

2

In [44]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [45]:
x = x.reshape(3,3)

In [46]:
x.shape

(3, 3)

In [47]:
x.flatten()#nd - 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# in 2d data by default slicing will be row wise
x[2:]

array([[7, 8, 9]])

In [51]:
x[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [36]:
x[:,0:2]

array([[4, 5],
       [6, 8],
       [8, 8]])